### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by WestFR** [dji-sdk/DJIWidget#14]
On pod install : 
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by TaylorsZ** [comment]
一样的问题，更新完SDK后就报这个错！！！！

**Comment by dji-dev** [comment]
Hi @TaylorsZ @WestFR , thanks for the feedbacks! Please update your DJIWidget to the latest 1.5 and check if the issue is fixed.

**Comment by WestFR** [comment]
@dji-dev, thanks for your reactivity !

The update of my DJIWiget to the latest version at this instant (1.5) are perfectly fixed my issue !
The app no produce build and run error and can get compile on phone and simulator.
