### ISSUE TITLE
Can't find FFmpeg header files

### ISSUE THREAD

**Issue by valentary** [dji-sdk/DJIWidget#3]
I created a demo project here : https://github.com/valentary/DJISDKTest/tree/DJIWidgetBuildError
The project will not build as it cannot find the header files from FFmpeg in DJICustomVideoFrameExtractor

It's a default single view project, all I did was to install the cocoapods and try to build.
We use use_frameworks! which seems to be the cause, 
I've tried various workarounds, but we either can't find the headers, or we get error with the FFmpeg static binary.

**Comment by dji-dev** [comment]
Hi @valentary ，please remove the "use_frameworks!" in the pod file. The issue should be fixed.

**Comment by valentary** [comment]
Hi, that's not really an option for us, we use many pods that require dynamic frameworks.  In particular, we do not wish to load the DJI SDK at startup, but load it when it is required.

**Comment by valentary** [comment]
It could be an option for us to add FFmpeg as a static library independently of DJIWidget

**Comment by SpencerKaiser** [comment]
@valentary I just opened [an issue for another problem](https://github.com/dji-sdk/DJIWidget/issues/4) with header files, maybe the temporary solution I provided in the edit will help you!

**Comment by dji-dev** [comment]
Hi @SpencerKaiser @valentary  , thanks for the feedbacks. We just release DJIWidget 1.1, now it supports dynamic framework, you can keep the `use_frameworks!` in the podfile for Swift project.

**Comment by valentary** [comment]
Just installed it now, works like a charm, we can connect and get the live stream, thanks!
