### ISSUE TITLE
Unable to find a specification for `DJIWidget (~> 1.0)`

### ISSUE THREAD

**Issue by dshackelford** [dji-sdk/DJIWidget#7]
Installing cocoa pods with DJIWidget does not work in DJISDK demo project. 

I tried running `pod install` to create a workspace and I get the following error in terminal:

>[!] Unable to find a specification for `DJIWidget (~> 1.0)`

Podfile Contents:
`# platform :ios, '9.0'

target 'DJISdkDemo' do
  pod 'DJI-SDK-iOS', '~> 4.7.1'
  pod 'DJIWidget', '~> 1.0'
end`

Thanks,
Dylan

**Comment by dji-dev** [comment]
Hi @dshackelford , please use `pod update` and `pod repo update` commands to update your local specs firstly.
